#!/usr/bin/env node

const redis = require('./lib/index')
const cli = redis.createClient(6379)

cli.info()(function * (err, info) {
  if (err) throw err

  const add = []
  const discard = []
  const commandsInfo = {}
  let commands = yield cli.command()

  commands = commands.map(function (command) {
    commandsInfo[command[0]] = command.slice(1)
    return command[0]
  })

  commands.reduce(function (add, command) {
    if (cli.clientCommands.indexOf(command) === -1) add.push(command)
    return add
  }, add)

  cli.clientCommands.reduce(function (discard, command) {
    if (commands.indexOf(command) === -1) discard.push(command)
    return discard
  }, discard)

  const all = {}
  Object.keys(commandsInfo).sort().forEach(function (command) {
    all[command] = commandsInfo[command]
  })

  console.log(all)
  console.log('Add:', add)
  console.log('Discard:', discard)
  console.log('Version:', info.redis_version)
  process.exit()
})()
